name: Playwright Tests
on:
  pull_request:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4, 5, 6]
        shardTotal: [6]
    steps:
      - uses: act10ns/slack@v2
        with:
          status: starting
          message: 'Starting Playwright tests...${{ matrix.shardIndex }}'
          matrix: ${{ toJson(matrix) }}
        if: always()

      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: Get installed Playwright version
        id: playwright-version
        run: |
          VERSION=$(cat ./package.json | grep '@playwright/test' | awk -F: '{ print $2 }' | sed 's/[",]//g' |tr  -d ^ | xargs)
          echo "Playwright version is: $VERSION"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Playwright Binaries
        id: cache-playwright
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        id: install-dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browser Chrome
        if: steps.cache-playwright.outputs.cache-hit != 'true'
        run: npx playwright install chromium

      - name: Run Static analysis
        run: npm run check

      - name: Run Playwright tests
        run: npx playwright test --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} --project UI_tests

      - name: Upload Allure Results
        id: upload-allure-results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.shardIndex }}
          path: ./report/allure-results
          if-no-files-found: ignore
          retention-days: 1

  generate-report:
    name: Generate Allure Report
    needs: test
    runs-on: ubuntu-latest
    if: always()
    env:
      SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
      - name: Install dependencies
        if: always()
        run: |
          npm ci
      - name: Generate and Publish Allure Report
        uses: Valiantsin2021/allure-shard-results-publish@1.0.1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-pattern: 'allure-results-*'
          report-title: 'Allure report for Playwright tests'
